services:
  - type: web
    name: auth_service
    env: docker
    plan: free
    dockerfilePath: ./authServer/Dockerfile
    dockerContext: ./authServer
    autoDeploy: true

  - type: web
    name: profile_service
    env: docker
    plan: free
    dockerfilePath: ./profileServer/Dockerfile
    dockerContext: ./profileServer
    autoDeploy: true

  - type: web
    name: blog_service
    env: docker
    plan: free
    dockerfilePath: ./blogServer/Dockerfile
    dockerContext: ./blogServer
    autoDeploy: true

  - type: web
    name: api_gateway
    env: docker
    plan: free
    dockerfilePath: ./api-gateway/Dockerfile
    dockerContext: ./api-gateway
    autoDeploy: true